// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://uruafniidrsoxskvmmro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVydWFmbmlpZHJzb3hza3ZtbXJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3OTg1MDAsImV4cCI6MjA3MTM3NDUwMH0.is5IpyTPBeODfcmYheosQR2UgDSdpMQyQxVAQh_lghY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);